class_name AchievementData

const ACHIEVEMENTS = [
	{"id": "first_blood", "name": "İlk Kan", "desc": "İlk düşmanı öldür", "icon": "⚔", "reward_gold": 50,
		"condition": {"type": "total_kills", "amount": 1}},
	{"id": "killer_100", "name": "Katliamcı", "desc": "Tek koşuda 100 düşman öldür", "icon": "💀", "reward_gold": 100,
		"condition": {"type": "single_run_kills", "amount": 100}},
	{"id": "killer_500", "name": "Makineli", "desc": "Tek koşuda 500 düşman öldür", "icon": "💀", "reward_gold": 200,
		"condition": {"type": "single_run_kills", "amount": 500}},
	{"id": "killer_1000", "name": "Tanrının Gazabı", "desc": "Tek koşuda 1000 düşman öldür", "icon": "👑", "reward_gold": 500,
		"condition": {"type": "single_run_kills", "amount": 1000}},
	{"id": "survive_10", "name": "Hayatta Kalan", "desc": "10 dakika hayatta kal", "icon": "⏱", "reward_gold": 100,
		"condition": {"type": "survival_time", "amount": 600}},
	{"id": "survive_20", "name": "Efsane", "desc": "20 dakika hayatta kal", "icon": "⏱", "reward_gold": 250,
		"condition": {"type": "survival_time", "amount": 1200}},
	{"id": "survive_30", "name": "Ölümsüz", "desc": "Oyunu bitir (30 dakika)", "icon": "🏆", "reward_gold": 1000,
		"condition": {"type": "won_game", "amount": 1}},
	{"id": "boss_first", "name": "Boss Katili", "desc": "İlk boss'u öldür", "icon": "👹", "reward_gold": 150,
		"condition": {"type": "total_bosses", "amount": 1}},
	{"id": "boss_10", "name": "Boss Avcısı", "desc": "Toplamda 10 boss öldür", "icon": "👹", "reward_gold": 300,
		"condition": {"type": "total_bosses", "amount": 10}},
	{"id": "evolution", "name": "Evrimci", "desc": "Bir silahı evrimleştir", "icon": "⚡", "reward_gold": 200,
		"condition": {"type": "got_evolution", "amount": 1}},
	{"id": "collector", "name": "Koleksiyoncu", "desc": "5 farklı karakterle oyna", "icon": "🎭", "reward_gold": 300,
		"condition": {"type": "unique_chars", "amount": 5}},
	{"id": "chest_50", "name": "Sandık Avcısı", "desc": "Toplamda 50 sandık aç", "icon": "📦", "reward_gold": 200,
		"condition": {"type": "total_chests", "amount": 50}},
	{"id": "rich", "name": "Zengin", "desc": "Toplamda 1000 altın kazan", "icon": "💰", "reward_gold": 150,
		"condition": {"type": "total_gold", "amount": 1000}},
	{"id": "unlock_chaos", "name": "Kaos'u Bul", "desc": "Kaos karakterini aç", "icon": "🎲", "reward_gold": 300,
		"condition": {"type": "char_unlocked", "char_id": "chaos"}},
	{"id": "unlock_omega", "name": "Omega'yı Bul", "desc": "Omega karakterini aç", "icon": "☠", "reward_gold": 500,
		"condition": {"type": "char_unlocked", "char_id": "omega"}},
]
