extends Resource
class_name CharacterData

const CHARACTERS = [
	# --- AÇIK KARAKTERLER (3) ---
	{
		"id": "warrior",
		"name": "Savaşçı",
		"description": "Güçlü ve dayanıklı.\n+10 başlangıç hasarı.",
		"color": "#3498DB",
		"start_weapon": "bullet",
		"bonus_damage": 10,
		"bonus_hp": 0,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "",
		"locked": false,
		"secret": false,
		"cost": 0,
		"unlock_hint": "",
		"unlock_condition": {},
		"origin_bonus": {"type": "damage_flat", "amount": 15, "penalty": "none"},
	},
	{
		"id": "mage",
		"name": "Büyücü",
		"description": "Alan hasarı uzmanı.\n+25 max can, Aura ile başlar.",
		"color": "#9B59B6",
		"start_weapon": "aura",
		"bonus_damage": 0,
		"bonus_hp": 25,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "",
		"locked": false,
		"secret": false,
		"cost": 0,
		"unlock_hint": "",
		"unlock_condition": {},
		"origin_bonus": {"type": "area_pct", "amount": 0.30, "penalty": "speed_pct", "penalty_amount": -0.15},
	},
	{
		"id": "vampire",
		"name": "Vampir",
		"description": "Kan içen avcı.\nCan çalma ile başlar.",
		"color": "#E74C3C",
		"start_weapon": "chain",
		"bonus_damage": 5,
		"bonus_hp": 0,
		"bonus_speed": 20,
		"bonus_armor": 0,
		"start_item": "lifesteal",
		"special": "",
		"locked": false,
		"secret": false,
		"cost": 0,
		"unlock_hint": "",
		"unlock_condition": {},
		"origin_bonus": {"type": "lifesteal_pct", "amount": 0.10, "penalty": "none"},
	},

	# --- KİLİTLİ BASE KARAKTERLER (7) ---
	{
		"id": "hunter",
		"name": "Avcı",
		"description": "Bumerang ustası.\n+%15 can çalma.",
		"color": "#27AE60",
		"start_weapon": "boomerang",
		"bonus_damage": 0,
		"bonus_hp": 0,
		"bonus_speed": 10,
		"bonus_armor": 0,
		"start_item": "",
		"special": "lifesteal_15",
		"locked": true,
		"secret": false,
		"cost": 200,
		"unlock_hint": "100 düşman öldür",
		"unlock_condition": {"type": "total_kills", "amount": 100},
		"origin_bonus": {"type": "projectile_count", "amount": 1, "penalty": "none"},
	},
	{
		"id": "stormer",
		"name": "Fırtına",
		"description": "Hız ustası.\nCooldown -%10.",
		"color": "#F1C40F",
		"start_weapon": "lightning",
		"bonus_damage": 0,
		"bonus_hp": 0,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "cooldown_10",
		"locked": true,
		"secret": false,
		"cost": 300,
		"unlock_hint": "5 dakika hayatta kal",
		"unlock_condition": {"type": "max_survival", "amount": 300},
		"origin_bonus": {"type": "cooldown_pct", "amount": -0.20, "penalty": "hp_pct", "penalty_amount": -0.20},
	},
	{
		"id": "frost",
		"name": "Buzcu",
		"description": "Buz ve yavaşlatma uzmanı.\nYavaşlatma süresi 2x.",
		"color": "#00BFFF",
		"start_weapon": "ice_ball",
		"bonus_damage": 0,
		"bonus_hp": 20,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "slow_double",
		"locked": true,
		"secret": false,
		"cost": 250,
		"unlock_hint": "Bir tank düşmanı öldür",
		"unlock_condition": {"type": "killed_tank", "amount": 1},
		"origin_bonus": {"type": "slow_double", "amount": 1, "penalty": "damage_pct", "penalty_amount": -0.15},
	},
	{
		"id": "shadow_walker",
		"name": "Gölge Yürüyücü",
		"description": "Sessiz ölüm.\n+30 hız, gölge orbu ile başlar.",
		"color": "#8E44AD",
		"start_weapon": "shadow",
		"bonus_damage": 0,
		"bonus_hp": 0,
		"bonus_speed": 30,
		"bonus_armor": 0,
		"start_item": "",
		"special": "",
		"locked": true,
		"secret": false,
		"cost": 400,
		"unlock_hint": "Toplam 300 düşman öldür",
		"unlock_condition": {"type": "total_kills", "amount": 300},
		"origin_bonus": {"type": "speed_pct", "amount": 0.25, "penalty": "hp_pct", "penalty_amount": -0.20},
	},
	{
		"id": "engineer",
		"name": "Mühendis",
		"description": "Lazer teknolojisi uzmanı.\n+%15 alan bonusu.",
		"color": "#E67E22",
		"start_weapon": "laser",
		"bonus_damage": 0,
		"bonus_hp": 0,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "area_15",
		"locked": true,
		"secret": false,
		"cost": 500,
		"unlock_hint": "8 dakika hayatta kal",
		"unlock_condition": {"type": "max_survival", "amount": 480},
		"origin_bonus": {"type": "single_weapon", "amount": 1, "penalty": "cooldown_pct", "penalty_amount": -0.70},
	},
	{
		"id": "paladin",
		"name": "Paladin",
		"description": "Kutsal savaşçı.\n+4 zırh, Holy Bullet ile başlar.",
		"color": "#ECF0F1",
		"start_weapon": "holy_bullet",
		"bonus_damage": 0,
		"bonus_hp": 30,
		"bonus_speed": 0,
		"bonus_armor": 4,
		"start_item": "",
		"special": "",
		"locked": true,
		"secret": false,
		"cost": 600,
		"unlock_hint": "Bir evrim silahı elde et",
		"unlock_condition": {"type": "evolution_obtained", "amount": 1},
		"origin_bonus": {"type": "armor_flat", "amount": 6, "penalty": "speed_pct", "penalty_amount": -0.15},
	},
	{
		"id": "blood_prince",
		"name": "Kan Prensi",
		"description": "Vampirin mirasçısı.\nXP +%20, Blood Boomerang ile başlar.",
		"color": "#C0392B",
		"start_weapon": "blood_boomerang",
		"bonus_damage": 5,
		"bonus_hp": 0,
		"bonus_speed": 15,
		"bonus_armor": 0,
		"start_item": "",
		"special": "xp_20",
		"locked": true,
		"secret": false,
		"cost": 400,
		"unlock_hint": "Vampir ile 5 dakika hayatta kal",
		"unlock_condition": {"type": "survive_as", "character": "vampire", "amount": 300},
		"origin_bonus": {"type": "xp_pct", "amount": 0.30, "penalty": "hp_pct", "penalty_amount": -0.15},
	},
	{
		"id": "nomad",
		"name": "Göçebe",
		"description": "Sürgün savaşçı.\nYakın menzilli Yelpaze Bıçak ile başlar.\nÖnce 175 düşman öldür, sonra 💰350 altınla satın al.",
		"color": "#D35400",
		"start_weapon": "fan_blade",
		"bonus_damage": 0,
		"bonus_hp": 0,
		"bonus_speed": 15,
		"bonus_armor": 0,
		"start_item": "",
		"special": "",
		"locked": true,
		"secret": false,
		"cost": 350,
		"unlock_hint": "Toplam 175 düşman öldür; kilidi açılınca 💰350 altınla satın alırsın.",
		"unlock_condition": {"type": "total_kills", "amount": 175},
		"origin_bonus": {"type": "damage_flat", "amount": 5, "penalty": "none"},
	},

	# --- SECRET KARAKTERLER (3) ---
	{
		"id": "death_knight",
		"name": "Ölüm Şövalyesi",
		"description": "Ölüm Lazeri ile başlar.\n+30 hasar, -50 HP, hasar 2x.",
		"color": "#8B0000",
		"start_weapon": "death_laser",
		"bonus_damage": 30,
		"bonus_hp": -50,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "damage_double",
		"locked": true,
		"secret": true,
		"cost": 0,
		"unlock_hint": "Tek bir koşuda 1000 düşman öldür.",
		"unlock_condition": {"type": "single_run_kills", "amount": 1000},
		"origin_bonus": {},
	},
	{
		"id": "chaos",
		"name": "Kaos",
		"description": "Rastgele silahlarla başlar.\nHer şey mümkün.",
		"color": "#FF6600",
		"start_weapon": "",
		"bonus_damage": 0,
		"bonus_hp": 0,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "random_weapons",
		"locked": true,
		"secret": true,
		"cost": 0,
		"unlock_hint": "5 farklı karakterle oyna.",
		"unlock_condition": {"type": "unique_chars_played", "amount": 5},
		"origin_bonus": {},
	},
	{
		"id": "omega",
		"name": "Omega",
		"description": "Tüm silahlar aktif.\n1 HP ile oyna. Ölmeden bitir.",
		"color": "#000080",
		"start_weapon": "bullet",
		"bonus_damage": 0,
		"bonus_hp": 0,
		"bonus_speed": 0,
		"bonus_armor": 0,
		"start_item": "",
		"special": "all_weapons_1hp",
		"locked": true,
		"secret": true,
		"cost": 0,
		"unlock_hint": "Gizli bir kod var...",
		"unlock_condition": {"type": "easter_egg"},
		"origin_bonus": {},
	},
]
